[package]
name = "jf"
version = "0.1.0"
edition = "2021"
authors = ["shua <itis@isthisa.email>"]

[build-dependencies]
lalrpop = "0.19.9"

[dependencies]
lalrpop-util = "0.19.9"
regex = "1"
codespan-reporting = "0.11.1"
